INSERT INTO Country VALUES (1, 'AF', 'Afghanistan');
INSERT INTO Country VALUES (2, 'AL', 'Albania');
INSERT INTO Country VALUES (3, 'DZ', 'Algeria');
INSERT INTO Country VALUES (4, 'DS', 'American Samoa');
INSERT INTO Country VALUES (5, 'AD', 'Andorra');
INSERT INTO Country VALUES (6, 'AO', 'Angola');
INSERT INTO Country VALUES (7, 'AI', 'Anguilla');
INSERT INTO Country VALUES (8, 'AQ', 'Antarctica');
INSERT INTO Country VALUES (9, 'AG', 'Antigua and Barbuda');
INSERT INTO Country VALUES (10, 'AR', 'Argentina');
INSERT INTO Country VALUES (11, 'AM', 'Armenia');
INSERT INTO Country VALUES (12, 'AW', 'Aruba');
INSERT INTO Country VALUES (13, 'AU', 'Australia');
INSERT INTO Country VALUES (14, 'AT', 'Austria');
INSERT INTO Country VALUES (15, 'AZ', 'Azerbaijan');
INSERT INTO Country VALUES (16, 'BS', 'Bahamas');
INSERT INTO Country VALUES (17, 'BH', 'Bahrain');
INSERT INTO Country VALUES (18, 'BD', 'Bangladesh');
INSERT INTO Country VALUES (19, 'BB', 'Barbados');
INSERT INTO Country VALUES (20, 'BY', 'Belarus');
INSERT INTO Country VALUES (21, 'BE', 'Belgium');
INSERT INTO Country VALUES (22, 'BZ', 'Belize');
INSERT INTO Country VALUES (23, 'BJ', 'Benin');
INSERT INTO Country VALUES (24, 'BM', 'Bermuda');
INSERT INTO Country VALUES (25, 'BT', 'Bhutan');
INSERT INTO Country VALUES (26, 'BO', 'Bolivia');
INSERT INTO Country VALUES (27, 'BA', 'Bosnia and Herzegovina');
INSERT INTO Country VALUES (28, 'BW', 'Botswana');
INSERT INTO Country VALUES (29, 'BV', 'Bouvet Island');
INSERT INTO Country VALUES (30, 'BR', 'Brazil');
INSERT INTO Country VALUES (31, 'IO', 'British Indian Ocean Territory');
INSERT INTO Country VALUES (32, 'BN', 'Brunei Darussalam');
INSERT INTO Country VALUES (33, 'BG', 'Bulgaria');
INSERT INTO Country VALUES (34, 'BF', 'Burkina Faso');
INSERT INTO Country VALUES (35, 'BI', 'Burundi');
INSERT INTO Country VALUES (36, 'KH', 'Cambodia');
INSERT INTO Country VALUES (37, 'CM', 'Cameroon');
INSERT INTO Country VALUES (38, 'CA', 'Canada');
INSERT INTO Country VALUES (39, 'CV', 'Cape Verde');
INSERT INTO Country VALUES (40, 'KY', 'Cayman Islands');
INSERT INTO Country VALUES (41, 'CF', 'Central African Republic');
INSERT INTO Country VALUES (42, 'TD', 'Chad');
INSERT INTO Country VALUES (43, 'CL', 'Chile');
INSERT INTO Country VALUES (44, 'CN', 'China');
INSERT INTO Country VALUES (45, 'CX', 'Christmas Island');
INSERT INTO Country VALUES (46, 'CC', 'Cocos (Keeling) Islands');
INSERT INTO Country VALUES (47, 'CO', 'Colombia');
INSERT INTO Country VALUES (48, 'KM', 'Comoros');
INSERT INTO Country VALUES (49, 'CG', 'Congo');
INSERT INTO Country VALUES (50, 'CK', 'Cook Islands');
INSERT INTO Country VALUES (51, 'CR', 'Costa Rica');
INSERT INTO Country VALUES (52, 'HR', 'Croatia (Hrvatska)');
INSERT INTO Country VALUES (53, 'CU', 'Cuba');
INSERT INTO Country VALUES (54, 'CY', 'Cyprus');
INSERT INTO Country VALUES (55, 'CZ', 'Czech Republic');
INSERT INTO Country VALUES (56, 'DK', 'Denmark');
INSERT INTO Country VALUES (57, 'DJ', 'Djibouti');
INSERT INTO Country VALUES (58, 'DM', 'Dominica');
INSERT INTO Country VALUES (59, 'DO', 'Dominican Republic');
INSERT INTO Country VALUES (60, 'TP', 'East Timor');
INSERT INTO Country VALUES (61, 'EC', 'Ecuador');
INSERT INTO Country VALUES (62, 'EG', 'Egypt');
INSERT INTO Country VALUES (63, 'SV', 'El Salvador');
INSERT INTO Country VALUES (64, 'GQ', 'Equatorial Guinea');
INSERT INTO Country VALUES (65, 'ER', 'Eritrea');
INSERT INTO Country VALUES (66, 'EE', 'Estonia');
INSERT INTO Country VALUES (67, 'ET', 'Ethiopia');
INSERT INTO Country VALUES (68, 'FK', 'Falkland Islands (Malvinas)');
INSERT INTO Country VALUES (69, 'FO', 'Faroe Islands');
INSERT INTO Country VALUES (70, 'FJ', 'Fiji');
INSERT INTO Country VALUES (71, 'FI', 'Finland');
INSERT INTO Country VALUES (72, 'FR', 'France');
INSERT INTO Country VALUES (73, 'FX', 'France, Metropolitan');
INSERT INTO Country VALUES (74, 'GF', 'French Guiana');
INSERT INTO Country VALUES (75, 'PF', 'French Polynesia');
INSERT INTO Country VALUES (76, 'TF', 'French Southern Territories');
INSERT INTO Country VALUES (77, 'GA', 'Gabon');
INSERT INTO Country VALUES (78, 'GM', 'Gambia');
INSERT INTO Country VALUES (79, 'GE', 'Georgia');
INSERT INTO Country VALUES (80, 'DE', 'Germany');
INSERT INTO Country VALUES (81, 'GH', 'Ghana');
INSERT INTO Country VALUES (82, 'GI', 'Gibraltar');
INSERT INTO Country VALUES (83, 'GK', 'Guernsey');
INSERT INTO Country VALUES (84, 'GR', 'Greece');
INSERT INTO Country VALUES (85, 'GL', 'Greenland');
INSERT INTO Country VALUES (86, 'GD', 'Grenada');
INSERT INTO Country VALUES (87, 'GP', 'Guadeloupe');
INSERT INTO Country VALUES (88, 'GU', 'Guam');
INSERT INTO Country VALUES (89, 'GT', 'Guatemala');
INSERT INTO Country VALUES (90, 'GN', 'Guinea');
INSERT INTO Country VALUES (91, 'GW', 'Guinea-Bissau');
INSERT INTO Country VALUES (92, 'GY', 'Guyana');
INSERT INTO Country VALUES (93, 'HT', 'Haiti');
INSERT INTO Country VALUES (94, 'HM', 'Heard and Mc Donald Islands');
INSERT INTO Country VALUES (95, 'HN', 'Honduras');
INSERT INTO Country VALUES (96, 'HK', 'Hong Kong');
INSERT INTO Country VALUES (97, 'HU', 'Hungary');
INSERT INTO Country VALUES (98, 'IS', 'Iceland');
INSERT INTO Country VALUES (99, 'IN', 'India');
INSERT INTO Country VALUES (100, 'IM', 'Isle of Man');
INSERT INTO Country VALUES (101, 'ID', 'Indonesia');
INSERT INTO Country VALUES (102, 'IR', 'Iran (Islamic Republic of)');
INSERT INTO Country VALUES (103, 'IQ', 'Iraq');
INSERT INTO Country VALUES (104, 'IE', 'Ireland');
INSERT INTO Country VALUES (105, 'IL', 'Israel');
INSERT INTO Country VALUES (106, 'IT', 'Italy');
INSERT INTO Country VALUES (107, 'CI', 'Ivory Coast');
INSERT INTO Country VALUES (108, 'JE', 'Jersey');
INSERT INTO Country VALUES (109, 'JM', 'Jamaica');
INSERT INTO Country VALUES (110, 'JP', 'Japan');
INSERT INTO Country VALUES (111, 'JO', 'Jordan');
INSERT INTO Country VALUES (112, 'KZ', 'Kazakhstan');
INSERT INTO Country VALUES (113, 'KE', 'Kenya');
INSERT INTO Country VALUES (114, 'KI', 'Kiribati');
INSERT INTO Country VALUES (115, 'KP', 'Korea, Democratic People''s Republic of');
INSERT INTO Country VALUES (116, 'KR', 'Korea, Republic of');
INSERT INTO Country VALUES (117, 'XK', 'Kosovo');
INSERT INTO Country VALUES (118, 'KW', 'Kuwait');
INSERT INTO Country VALUES (119, 'KG', 'Kyrgyzstan');
INSERT INTO Country VALUES (120, 'LA', 'Lao People''s Democratic Republic');
INSERT INTO Country VALUES (121, 'LV', 'Latvia');
INSERT INTO Country VALUES (122, 'LB', 'Lebanon');
INSERT INTO Country VALUES (123, 'LS', 'Lesotho');
INSERT INTO Country VALUES (124, 'LR', 'Liberia');
INSERT INTO Country VALUES (125, 'LY', 'Libyan Arab Jamahiriya');
INSERT INTO Country VALUES (126, 'LI', 'Liechtenstein');
INSERT INTO Country VALUES (127, 'LT', 'Lithuania');
INSERT INTO Country VALUES (128, 'LU', 'Luxembourg');
INSERT INTO Country VALUES (129, 'MO', 'Macau');
INSERT INTO Country VALUES (130, 'MK', 'Macedonia');
INSERT INTO Country VALUES (131, 'MG', 'Madagascar');
INSERT INTO Country VALUES (132, 'MW', 'Malawi');
INSERT INTO Country VALUES (133, 'MY', 'Malaysia');
INSERT INTO Country VALUES (134, 'MV', 'Maldives');
INSERT INTO Country VALUES (135, 'ML', 'Mali');
INSERT INTO Country VALUES (136, 'MT', 'Malta');
INSERT INTO Country VALUES (137, 'MH', 'Marshall Islands');
INSERT INTO Country VALUES (138, 'MQ', 'Martinique');
INSERT INTO Country VALUES (139, 'MR', 'Mauritania');
INSERT INTO Country VALUES (140, 'MU', 'Mauritius');
INSERT INTO Country VALUES (141, 'TY', 'Mayotte');
INSERT INTO Country VALUES (142, 'MX', 'Mexico');
INSERT INTO Country VALUES (143, 'FM', 'Micronesia, Federated States of');
INSERT INTO Country VALUES (144, 'MD', 'Moldova, Republic of');
INSERT INTO Country VALUES (145, 'MC', 'Monaco');
INSERT INTO Country VALUES (146, 'MN', 'Mongolia');
INSERT INTO Country VALUES (147, 'ME', 'Montenegro');
INSERT INTO Country VALUES (148, 'MS', 'Montserrat');
INSERT INTO Country VALUES (149, 'MA', 'Morocco');
INSERT INTO Country VALUES (150, 'MZ', 'Mozambique');
INSERT INTO Country VALUES (151, 'MM', 'Myanmar');
INSERT INTO Country VALUES (152, 'NA', 'Namibia');
INSERT INTO Country VALUES (153, 'NR', 'Nauru');
INSERT INTO Country VALUES (154, 'NP', 'Nepal');
INSERT INTO Country VALUES (155, 'NL', 'Netherlands');
INSERT INTO Country VALUES (156, 'AN', 'Netherlands Antilles');
INSERT INTO Country VALUES (157, 'NC', 'New Caledonia');
INSERT INTO Country VALUES (158, 'NZ', 'New Zealand');
INSERT INTO Country VALUES (159, 'NI', 'Nicaragua');
INSERT INTO Country VALUES (160, 'NE', 'Niger');
INSERT INTO Country VALUES (161, 'NG', 'Nigeria');
INSERT INTO Country VALUES (162, 'NU', 'Niue');
INSERT INTO Country VALUES (163, 'NF', 'Norfolk Island');
INSERT INTO Country VALUES (164, 'MP', 'Northern Mariana Islands');
INSERT INTO Country VALUES (165, 'NO', 'Norway');
INSERT INTO Country VALUES (166, 'OM', 'Oman');
INSERT INTO Country VALUES (167, 'PK', 'Pakistan');
INSERT INTO Country VALUES (168, 'PW', 'Palau');
INSERT INTO Country VALUES (169, 'PS', 'Palestine');
INSERT INTO Country VALUES (170, 'PA', 'Panama');
INSERT INTO Country VALUES (171, 'PG', 'Papua New Guinea');
INSERT INTO Country VALUES (172, 'PY', 'Paraguay');
INSERT INTO Country VALUES (173, 'PE', 'Peru');
INSERT INTO Country VALUES (174, 'PH', 'Philippines');
INSERT INTO Country VALUES (175, 'PN', 'Pitcairn');
INSERT INTO Country VALUES (176, 'PL', 'Poland');
INSERT INTO Country VALUES (177, 'PT', 'Portugal');
INSERT INTO Country VALUES (178, 'PR', 'Puerto Rico');
INSERT INTO Country VALUES (179, 'QA', 'Qatar');
INSERT INTO Country VALUES (180, 'RE', 'Reunion');
INSERT INTO Country VALUES (181, 'RO', 'Romania');
INSERT INTO Country VALUES (182, 'RU', 'Russian Federation');
INSERT INTO Country VALUES (183, 'RW', 'Rwanda');
INSERT INTO Country VALUES (184, 'KN', 'Saint Kitts and Nevis');
INSERT INTO Country VALUES (185, 'LC', 'Saint Lucia');
INSERT INTO Country VALUES (186, 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO Country VALUES (187, 'WS', 'Samoa');
INSERT INTO Country VALUES (188, 'SM', 'San Marino');
INSERT INTO Country VALUES (189, 'ST', 'Sao Tome and Principe');
INSERT INTO Country VALUES (190, 'SA', 'Saudi Arabia');
INSERT INTO Country VALUES (191, 'SN', 'Senegal');
INSERT INTO Country VALUES (192, 'RS', 'Serbia');
INSERT INTO Country VALUES (193, 'SC', 'Seychelles');
INSERT INTO Country VALUES (194, 'SL', 'Sierra Leone');
INSERT INTO Country VALUES (195, 'SG', 'Singapore');
INSERT INTO Country VALUES (196, 'SK', 'Slovakia');
INSERT INTO Country VALUES (197, 'SI', 'Slovenia');
INSERT INTO Country VALUES (198, 'SB', 'Solomon Islands');
INSERT INTO Country VALUES (199, 'SO', 'Somalia');
INSERT INTO Country VALUES (200, 'ZA', 'South Africa');
INSERT INTO Country VALUES (201, 'GS', 'South Georgia South Sandwich Islands');
INSERT INTO Country VALUES (202, 'SS', 'South Sudan');
INSERT INTO Country VALUES (203, 'ES', 'Spain');
INSERT INTO Country VALUES (204, 'LK', 'Sri Lanka');
INSERT INTO Country VALUES (205, 'SH', 'St. Helena');
INSERT INTO Country VALUES (206, 'PM', 'St. Pierre and Miquelon');
INSERT INTO Country VALUES (207, 'SD', 'Sudan');
INSERT INTO Country VALUES (208, 'SR', 'Suriname');
INSERT INTO Country VALUES (209, 'SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO Country VALUES (210, 'SZ', 'Swaziland');
INSERT INTO Country VALUES (211, 'SE', 'Sweden');
INSERT INTO Country VALUES (212, 'CH', 'Switzerland');
INSERT INTO Country VALUES (213, 'SY', 'Syrian Arab Republic');
INSERT INTO Country VALUES (214, 'TW', 'Taiwan');
INSERT INTO Country VALUES (215, 'TJ', 'Tajikistan');
INSERT INTO Country VALUES (216, 'TZ', 'Tanzania, United Republic of');
INSERT INTO Country VALUES (217, 'TH', 'Thailand');
INSERT INTO Country VALUES (218, 'TG', 'Togo');
INSERT INTO Country VALUES (219, 'TK', 'Tokelau');
INSERT INTO Country VALUES (220, 'TO', 'Tonga');
INSERT INTO Country VALUES (221, 'TT', 'Trinidad and Tobago');
INSERT INTO Country VALUES (222, 'TN', 'Tunisia');
INSERT INTO Country VALUES (223, 'TR', 'Turkey');
INSERT INTO Country VALUES (224, 'TM', 'Turkmenistan');
INSERT INTO Country VALUES (225, 'TC', 'Turks and Caicos Islands');
INSERT INTO Country VALUES (226, 'TV', 'Tuvalu');
INSERT INTO Country VALUES (227, 'UG', 'Uganda');
INSERT INTO Country VALUES (228, 'UA', 'Ukraine');
INSERT INTO Country VALUES (229, 'AE', 'United Arab Emirates');
INSERT INTO Country VALUES (230, 'GB', 'United Kingdom');
INSERT INTO Country VALUES (231, 'US', 'United States');
INSERT INTO Country VALUES (232, 'UM', 'United States minor outlying islands');
INSERT INTO Country VALUES (233, 'UY', 'Uruguay');
INSERT INTO Country VALUES (234, 'UZ', 'Uzbekistan');
INSERT INTO Country VALUES (235, 'VU', 'Vanuatu');
INSERT INTO Country VALUES (236, 'VA', 'Vatican City State');
INSERT INTO Country VALUES (237, 'VE', 'Venezuela');
INSERT INTO Country VALUES (238, 'VN', 'Vietnam');
INSERT INTO Country VALUES (239, 'VG', 'Virgin Islands (British)');
INSERT INTO Country VALUES (240, 'VI', 'Virgin Islands (U.S.)');
INSERT INTO Country VALUES (241, 'WF', 'Wallis and Futuna Islands');
INSERT INTO Country VALUES (242, 'EH', 'Western Sahara');
INSERT INTO Country VALUES (243, 'YE', 'Yemen');
INSERT INTO Country VALUES (244, 'ZR', 'Zaire');
INSERT INTO Country VALUES (245, 'ZM', 'Zambia');
INSERT INTO Country VALUES (246, 'ZW', 'Zimbabwe');